"""
Phase 4.4 - Report Summarizer: Auto-generate executive summaries from data
"""
import duckdb
from datetime import datetime
from openai import OpenAI
from config import LLM_API_KEY, LLM_BASE_URL, LLM_MODEL, DUCKDB_PATH

client = OpenAI(api_key=LLM_API_KEY, base_url=LLM_BASE_URL)

SUMMARY_PROMPT = """You are a business analyst creating executive summaries.

Given supply chain data, write a concise executive summary with:

1. **Key Metrics** (3-4 bullet points with numbers)
2. **Performance Highlights** (what's going well)
3. **Areas of Concern** (issues needing attention)
4. **Recommendations** (2-3 actionable items)

Style: Professional, concise, data-driven. Use actual numbers from the data.
Length: 200-300 words max.
"""

def fetch_report_data(days: int = 30) -> dict:
    """Fetch comprehensive data for summarization"""
    con = duckdb.connect(str(DUCKDB_PATH), read_only=True)
    
    data = {}
    
    queries = {
        "kpis": f"""
            SELECT 
                SUM(revenue) as total_revenue,
                SUM(units_sold) as total_units,
                COUNT(DISTINCT sku) as active_skus,
                COUNT(DISTINCT store_id) as active_stores,
                COUNT(*) as transactions
            FROM main_features.demand_features
            WHERE ds >= (SELECT MAX(ds) - INTERVAL '{days} days' FROM main_features.demand_features)
        """,
        
        "top_performers": """
            SELECT sku, SUM(revenue) as revenue, SUM(units_sold) as units
            FROM main_features.demand_features
            WHERE ds >= (SELECT MAX(ds) - INTERVAL '30 days' FROM main_features.demand_features)
            GROUP BY sku ORDER BY revenue DESC LIMIT 5
        """,
        
        "bottom_performers": """
            SELECT sku, SUM(revenue) as revenue, SUM(units_sold) as units
            FROM main_features.demand_features
            WHERE ds >= (SELECT MAX(ds) - INTERVAL '30 days' FROM main_features.demand_features)
            GROUP BY sku ORDER BY revenue ASC LIMIT 5
        """,
        
        "store_performance": """
            SELECT store_id, SUM(revenue) as revenue
            FROM main_features.demand_features
            WHERE ds >= (SELECT MAX(ds) - INTERVAL '30 days' FROM main_features.demand_features)
            GROUP BY store_id ORDER BY revenue DESC LIMIT 5
        """,
        
        "daily_trend": """
            SELECT ds, SUM(revenue) as daily_revenue, SUM(units_sold) as daily_units
            FROM main_features.demand_features
            WHERE ds >= (SELECT MAX(ds) - INTERVAL '30 days' FROM main_features.demand_features)
            GROUP BY ds ORDER BY ds
        """,
        
        "anomaly_summary": """
            SELECT 
                COUNT(*) as total_anomalies,
                COUNT(DISTINCT sku) as affected_skus
            FROM main_features.anomalies
            WHERE is_anomaly = true
              AND ds >= (SELECT MAX(ds) - INTERVAL '30 days' FROM main_features.demand_features)
        """
    }
    
    for name, sql in queries.items():
        try:
            df = con.execute(sql).fetchdf()
            data[name] = df.to_dict('records')
        except Exception as e:
            data[name] = f"Query failed: {e}"
    
    con.close()
    return data

def generate_summary(period_days: int = 30) -> str:
    """Generate executive summary"""
    data = fetch_report_data(period_days)
    
    prompt = f"""
Generate an executive summary for Quantum Bricks supply chain operations.
Period: Last {period_days} days

Data:
KPIs: {data.get('kpis', [])}
Top Performing SKUs: {data.get('top_performers', [])}
Bottom Performing SKUs: {data.get('bottom_performers', [])}
Store Performance: {data.get('store_performance', [])}
Daily Trend: {data.get('daily_trend', [])[:7]}  # Last 7 days sample
Anomaly Summary: {data.get('anomaly_summary', [])}
"""
    
    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {"role": "system", "content": SUMMARY_PROMPT},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3
    )
    
    return response.choices[0].message.content

def generate_full_report(period_days: int = 30, output_file: str = None) -> str:
    """Generate and optionally save full report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    summary = generate_summary(period_days)
    
    report = f"""
================================================================================
QUANTUM BRICKS - EXECUTIVE SUMMARY REPORT
Generated: {timestamp}
Period: Last {period_days} days
================================================================================

{summary}

================================================================================
Report generated by Phase 4 LLM Integration
================================================================================
"""
    
    if output_file:
        with open(output_file, 'w') as f:
            f.write(report)
        print(f"📄 Report saved to: {output_file}")
    
    return report

if __name__ == "__main__":
    print("=" * 50)
    print("Quantum Bricks - Report Summarizer")
    print("=" * 50)
    
    # Generate 30-day summary
    report = generate_full_report(
        period_days=30,
        output_file="executive_summary.txt"
    )
    print(report)
    
    # Option for weekly report
    print("\n" + "=" * 50)
    print("Generating weekly summary...")
    weekly = generate_summary(period_days=7)
    print(weekly)
